const expenseData = [
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-01",
    amount: "6.20",
    name: "Ah ma chi mian",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "transport",
    date: "2022-07-01",
    amount: "12",
    name: "Grab",
    description: "grab to town",
  },
  {
    user_id: "",
    budget_id: "",
    category: "house",
    date: "2022-07-02",
    amount: "33.30",
    name: "house",
    description: "portable vacuum, ink",
  },
  {
    user_id: "",
    budget_id: "",
    category: "shopping",
    date: "2022-07-03",
    amount: "73",
    name: "books",
    description: "kinokuniya books",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-03",
    amount: "5",
    name: "wanton mee",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "house",
    date: "2022-07-04",
    amount: "37.95",
    name: "hair products",
    description: "shampoo, conditioner",
  },
  {
    user_id: "",
    budget_id: "",
    category: "transport",
    date: "2022-07-04",
    amount: "16.80",
    name: "Grab",
    description: "grab to home from town",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-05",
    amount: "13.50",
    name: "groceries",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-05",
    amount: "31.30",
    name: "food",
    description: "fishhead curry",
  },
  {
    user_id: "",
    budget_id: "",
    category: "shopping",
    date: "2022-07-06",
    amount: "9.90",
    name: "shopping",
    description: "decorative items",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-06",
    amount: "4",
    name: "herbal tea",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-07",
    amount: "51.50",
    name: "food",
    description: "ichiban",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-07",
    amount: "29.60",
    name: "groceries",
    description: "fairprice",
  },
  {
    user_id: "",
    budget_id: "",
    category: "transport",
    date: "2022-07-08",
    amount: "50",
    name: "ezlink",
    description: "top up card",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-10",
    amount: "10",
    name: "food",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "medical",
    date: "2022-07-10",
    amount: "5.20",
    name: "medical",
    description: "plaster",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-11",
    amount: "7.20",
    name: "food",
    description: "Macdonalds mcspicy",
  },
  {
    user_id: "",
    budget_id: "",
    category: "shopping",
    date: "2022-07-11",
    amount: "49.90",
    name: "clothes",
    description: "dress",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-13",
    amount: "5.60",
    name: "food",
    description: "char kway tiao",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-13",
    amount: "7.90",
    name: "food",
    description: "chicken rice set",
  },
  {
    user_id: "",
    budget_id: "",
    category: "transport",
    date: "2022-07-14",
    amount: "18",
    name: "grab",
    description: "grab to work",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-14",
    amount: "18",
    name: "grab",
    description: "genki",
  },
  {
    user_id: "",
    budget_id: "",
    category: "personal care",
    date: "2022-07-14",
    amount: "69.20",
    name: "cosmetics",
    description: "foundation",
  },
  {
    user_id: "",
    budget_id: "",
    category: "transport",
    date: "2022-07-15",
    amount: "27",
    name: "grab",
    description: "grab to joo koon",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-16",
    amount: "83.90",
    name: "grab",
    description: "dinner with parents",
  },
  {
    user_id: "",
    budget_id: "",
    category: "shopping",
    date: "2022-07-17",
    amount: "29.50",
    name: "shopping",
    description: "phone charger",
  },
  {
    user_id: "",
    budget_id: "",
    category: "gifts",
    date: "2022-07-18",
    amount: "29.50",
    name: "present",
    description: "bro's bday",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-18",
    amount: "9.50",
    name: "food",
    description: "korean food",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-19",
    amount: "15.50",
    name: "food",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "shopping",
    date: "2022-07-20",
    amount: "69.90",
    name: "clothes",
    description: "dress",
  },
  {
    user_id: "",
    budget_id: "",
    category: "others",
    date: "2022-07-20",
    amount: "40.90",
    name: "vitamins",
    description: "vit c",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-21",
    amount: "3.50",
    name: "food",
    description: "fishball noodles",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-21",
    amount: "7.50",
    name: "food",
    description: "starbucks",
  },
  {
    user_id: "",
    budget_id: "",
    category: "medical",
    date: "2022-07-22",
    amount: "79",
    name: "medical",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-23",
    amount: "5.50",
    name: "food",
    description: "fishsoup",
  },
  {
    user_id: "",
    budget_id: "",
    category: "transport",
    date: "2022-07-24",
    amount: "18",
    name: "grab",
    description: "grab to work",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-24",
    amount: "4.10",
    name: "food",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-25",
    amount: "8.10",
    name: "food",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "house",
    date: "2022-07-26",
    amount: "28.10",
    name: "house",
    description: "containers",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-27",
    amount: "83.10",
    name: "food",
    description: "kbbq with family",
  },
  {
    user_id: "",
    budget_id: "",
    category: "transport",
    date: "2022-07-27",
    amount: "9",
    name: "grab",
    description: "grab to home",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-29",
    amount: "15",
    name: "groceries",
    description: "fairprice",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-30",
    amount: "7.30",
    name: "food",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "food",
    date: "2022-07-30",
    amount: "6.00",
    name: "food",
    description: "",
  },
  {
    user_id: "",
    budget_id: "",
    category: "personal care",
    date: "2022-07-31",
    amount: "19.90",
    name: "personal care",
    description: "bottle",
  },
];
